<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="7" time="0.156" timestamp="2021-05-31T22:30:14.125912" hostname="DESKTOP-II93GLK"><testcase classname="test_Activity23" name="test_sumOfNumbers" time="0.002" /><testcase classname="test_Activity24" name="test_bank[30-10-20]" time="0.002" /><testcase classname="test_Activity24" name="test_bank[20-2-18]" time="0.002" /><testcase classname="test_Calculator" name="test_sum" time="0.002" /><testcase classname="test_Calculator" name="test_multiply" time="0.001" /><testcase classname="test_Calculator" name="test_division" time="0.001" /><testcase classname="test_Calculator" name="test_subtract" time="0.001"><failure message="assert (30 - 10) == 40">@pytest.mark.activity
    def test_subtract():
        num1 = 10
        num2 = 30
&gt;       assert num2-num1==40
E       assert (30 - 10) == 40

test_Calculator.py:24: AssertionError</failure></testcase></testsuite></testsuites>